name: Auto Run Runner H Workflow

on:
  schedule:
    # Runs daily at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  run-runnerh:
    runs-on: ubuntu-latest

    env:
      # Runner H authentication (set these secrets in GitHub repo Settings > Secrets)
      RUNNERH_API_KEY: ${{ secrets.RUNNERH_API_KEY }}

      # Email SMTP credentials for sending newsletter
      EMAIL_SMTP_USER: ${{ secrets.EMAIL_SMTP_USER }}
      EMAIL_SMTP_PASS: ${{ secrets.EMAIL_SMTP_PASS }}

      # Slack Webhook URL for posting newsletter to Slack channel
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Runner H CLI
        run: |
          # Adjust this installation command as per Runner H documentation
          curl -fsSL https://runnerh.example.com/install.sh | bash

      - name: Run Runner H workflow
        run: |
          runnerh run --config runnerh.yaml
